name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  # running control
  dryRun:
    description: dryRun option
  maxIterations:
    description:
      'an optional setting for the maximum number of iterations we invokes
      openAI endpoint'
  # model option
  baseURL:
    description: 'url for your openAI API endpoint'
  apiKey:
    description: 'apikey for your openAI API endpoint'
  model:
    description: 'the model we are going to interact with openAI API endpoint'
  prompt:
    description:
      'the prompt string your are going to talk with openAI API endpoint'
  # feature selection
  runType:
    description: 'action type, jsunittest or godoc'
  dirPath:
    description: 'the dir path of your source code'
  # feature specific
  deploymentfile:
    description: 'the deployment yaml if you use CVE2Deployment'

runs:
  using: node20
  main: dist/index.js
