name: Go Doc Generate

on:
  workflow_dispatch:

permissions: write-all

test-godocgeneration:
  name: test-godocgeneration
  runs-on: ubuntu-latest
  uses: ./.github/workflows/goDoc.yml
  with:
    dryrun: false
    build_image: false
