name: Generate JS unittests files
on:
  workflow_dispatch:

permissions: write-all

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: use this action to generate unit test
        id: Lint with LLM
        uses: SamYuan1990/OpenAI_CodeAgent-action@main
        with:
          baseURL: https://api.deepseek.com
          apiKey: ${{ secrets.API_KEY }}
          model: deepseek-chat
          dirPath: ./src
          maxIterations: 3
          runType: jsunittest

      - uses: actions/upload-artifact@v4
        with:
          name: LLM_output
          path: GenAI_output

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: auto-pr-branch # 新分支名称
          base: main # 目标分支
          title: 'Automated PR: Update unit test files'
          body: 'This is an automated pull request created by GitHub Actions.'
          commit-message: 'Auto-generated changes'
          labels: automated # 可选：为 PR 添加标签
