name: C Vulnerabilities scan

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test-ccodescan:
    name: test-ccodescan
    uses: ./.github/workflows/cScan.yml
    with:
      dryrun: true
      build_image: true
