name: CVE to Deployment

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test-cvetodeployment:
    name: test-cvetodeployment
    uses: ./.github/workflows/CVE_to_Deployment.yml
    with:
      dryrun: false
      build_image: false
