name: CVE to Deployment

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test-cvewithdependency:
    name: test-cvewithdependency
    uses: ./.github/workflows/CVE_Dependency.yml
    with:
      dryrun: false
      build_image: false
