name: Generate JS unittests files
on:
  workflow_dispatch:

permissions: write-all

test-jsunittest:
  name: test-cvetodeployment
  runs-on: ubuntu-latest
  uses: ./.github/workflows/jsunittest.yml
  with:
    dryrun: false
    build_image: false
