name: go doc generate
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      dryrun:
        description: 'running mode'
        required: true
        default: true
        type: boolean
      build_image:
        description: 'build image or not'
        required: true
        default: false
        type: boolean

jobs:
  test-go-doc-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action repo for latest image
        if: ${{ inputs.build_image == true }}
        id: checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        if: ${{ inputs.build_image == true }}
        uses: docker/setup-buildx-action@v3
      - name: run local dev script
        if: ${{ inputs.build_image == true }}
        id: local-image-build
        run: |
          docker build -t ghcr.io/samyuan1990/openai_codeagent-action:latest .
      - name: Checkout
        id: checkout_target
        uses: actions/checkout@v4
        with:
          repository: SamYuan1990/kubeedge
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - name: Install dependencies
        run: |
          command -v ginkgo || go install github.com/onsi/ginkgo/v2/ginkgo@v2.9.5
      - name: unittest
        id: unittest
        run: |
          make test PROFILE=y
      - name: use this action to generate unit test
        id: Lint_with_LLM
        uses: ./
        with:
          baseURL: https://api.deepseek.com
          apiKey: dummy
          model: deepseek-chat
          dirPath: '/workdir'
          maxIterations: 1
          runType: godoc
          dryRun: ${{ inputs.dryrun }}
      - name: output check
        shell: bash
        run: |
          echo '${{ steps.test-action.outputs.LLMresponse }}'
          echo '${{ steps.test-action.outputs.final_prompt }}'
          echo '${{ steps.test-action.outputs.avg_prompt_precent }}'
          echo '${{ steps.test-action.outputs.avg_content_precent }}'

      - name: Create new issue
        uses: imjohnbo/issue-bot@v3
        if: ${{ inputs.dryrun == false }}
        with:
          title: CVE cross check with deployment
          body: |-
            :wave: Hi maintainers, here is LLM's deployment suggested according to your CVSS scan result.
            ${{ steps.Lint_with_LLM.outputs.LLMresponse }}
