name: Your Own CVE Dependencies
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      your_repo:
        description: 'your repo for checkout action'
        required: true
        type: string

jobs:
  test-cvewithdependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target repo
        id: checkout_target
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.your_repo }}
      - name: use this action to generate suggestion for deployment settings
        id: Lint_with_LLM
        uses: SamYuan1990/OpenAI_CodeAgent-action@main
        with:
          baseURL: https://api.deepseek.com
          apiKey: ${{ secrets.API_KEY }}
          model: deepseek-chat
          dirpath: '/workdir'
          runType: CVEDeep
      - name: output check
        shell: bash
        run: |
          echo '${{ steps.Lint_with_LLM.outputs.avg_prompt_precent }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_content_precent }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_time_usage }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_inputToken }}'
          echo '${{ steps.Lint_with_LLM.outputs.avg_outputToken }}'

      - name: Upload Artifact
        id: upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            cve.json
            GenAI_output
